services:
  backend:
    build: 
      context: ./Backend-Spring-Boot/Bluecrew-api/api
    container_name: spring-api
    # Quitamos ports: 8080:8080 para que solo Nginx hable con él
    networks:
      - app-network
    volumes:
      - uploads_volume:/app/uploads

  frontend:
    build: ./Frontend-React
    container_name: react-web
    # Quitamos ports: 80:80 porque ahora el puerto 80 lo usará el Proxy
    depends_on:
      - backend
    networks:
      - app-network

  nginx-proxy:
    image: nginx:alpine
    container_name: bluecrew_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads_volume: