server {
    listen 80;
    server_name bluecrew;

    # Configuración para el Frontend (React)
    location / {
        proxy_pass http://react-web:80; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Configuración para el Backend (Spring Boot)
    # Todas las llamadas que empiecen por /api irán al backend
    location /api {
        proxy_pass http://spring-api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}